version: '3.9'
services:
  mongo:
    image: mongo:focal
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5000:5000'
    volumes:
      - .:/app/
      - ./node_modules:/app/node_modules
    environment:
      - DATABASE_URL=mongodb://mongo:27017
      - PORT=5000
    depends_on:
      - mongo
volumes:
  mongo:
